# You can find the default config with description of parameters here:
# https://github.com/arboriginal/SCT-PlayerTracker/blob/master/src/settings.yml
#
# Permissions for this tracker are listed here:
# https://github.com/arboriginal/SCT-PlayerTracker/blob/master/README.md#permissions

settings:
  check_update: true # If true, when you (re)load the plugin, it try to check if a new version is available
  autoload_target: false # If true, permissions "scompass.track.auto.PLAYER.<name>" are activated
  inactive_target: false # If true, inactive targets will be added to compasses too (can affect performances and disturb display)

  symbol: "§a§l♙" # Symbol displayed on the compass to represent this kind of trackers positions.
  temp:   "♃"     # Advanced: Symbol temporary used by the plugin, must be unique, 1 char and not used in "symbol".

  request_duration: 120 # Duration (in seconds) before a tracking request expires.
  auto_disabled: 5 # If player closer than this (in blocks) from the target, the tracking stop automatically (0 to disable).

  limits:
    START: 1 # Number of maximum simultaneous positions a player (from this tracker) can track

  # Require settings.inactive_target: true
  inactive_symbol: "§7♙" # Symbol displayed on the compass to represent inactive targets of this kind of trackers positions.
  inactive_temp:   "☳"   # Advanced: Symbol temporary used by the plugin, must be unique, 1 char and not used in "symbol" nor "inactive_symbol".

locales:
  en:
    name: "player" # Only use alphabetic and numeric values, not space

    list: "{prefix}&rTracked players: {list}."
    list_empty: "{prefix}&rNo player tracked."

    ASK: "{prefix}&rTracking request sent to {target}."
    START: "{prefix}&6You are now tracking &e{target}&6."
    STOP: "{prefix}&6You no longer track &e{target}&6."

    request:
      message: |
        {prefix}&8--------------------------------------
        &8|
        &8|                 &e{player} &7want to track you.
        &8|
        &8|                   &8[ {DENY} &8] &f/&8 [ {ACCEPT} &8] &f?
        &8|
        &8----------------------------------------------------
      ACCEPT: "&a&lACCEPT"
      ACCEPT_hover: |
        Click to &e&laccept
        &7 -- or type --
        &c{command}
      DENY: "&c&lDENY"
      DENY_hover: |
        Click to &e&ldeny
        &7 -- or type --
        &c{command}
      accepted:
        player: "{prefix}&e{target}&r has &aaccepted&r your request."
        target: "{prefix}&e{player}&r is now tracking you..."
        player_limit_reached: "{prefix}&e{target}&r has &aaccepted&r your request, but you cannot track more players."
        target_limit_reached: "{prefix}&e{player}&r cannot track more players and is NOT tracking you for now..."
      refused:
        player: "{prefix}&e{target}&r has &crefused&r your request."
        target: "{prefix}&e{player}&r will not track you."
      expired: "{prefix}&cNo pending request from &e{player}&c."

    help:
      noargs: |
        &r- &c/{command} &e{tracker}
        &7  Show list of players you are currently tracking.
      ASK: |
        &r- &c/{command} &e{tracker} &6{ASK} &3<name>
        &7  Ask to a player to track his position.
      START: |
        &r- &c/{command} &e{tracker} &6{START} &3<name>
        &7  Begin the tracking of this player (without asking).
      STOP: |
        &r- &c/{command} &e{tracker} &6{STOP} &3<name>
        &7  End the tracking of this player.

    target_auto_disabled: "{prefix}&3You've reached &b{target}&3, tracking disabled in &b{tracker}&3 tracker."

  fr:
    name: "joueur" # N'utilise que des chiffres et des lettres, pas d'espace

    list: "{prefix}&rJoueurs pistés : {list}."
    list_empty: "{prefix}&rAucun joueur pisté."

    ASK: "{prefix}&rDemande pistage envoyée à {target}."
    START: "{prefix}&6Tu pistes maintenant &e{target}&6."
    STOP: "{prefix}&6Tu ne pistes plus &e{target}&6."

    request:
      message: |
        {prefix}&8--------------------------------------
        &8|
        &8|                 &e{player} &7veut te pister.
        &8|
        &8|                   &8[ {DENY} &8] &f/&8 [ {ACCEPT} &8] &f?
        &8|
        &8----------------------------------------------------
      ACCEPT: "&a&lACCEPTER"
      ACCEPT_hover: |
        Clique pour &e&laccepter
        &7 -- ou tape --
        &c{command}
      DENY: "&c&lREFUSER"
      DENY_hover: |
        Clique pour &e&lrefuser
        &7 -- ou tape --
        &c{command}
      accepted:
        player: "{prefix}&e{target}&r a &aaccepté&r ta demande."
        target: "{prefix}&e{player}&r te pistes à présent..."
        player_limit_reached: "{prefix}&e{target}&r a &aaccepté&r ta demande, mais tu ne peux pas pister d'autre joueurs."
        target_limit_reached: "{prefix}&e{player}&r ne peux pas pister d'autre joueurs pour le moment et ne te pistes donc pas..."
      refused:
        player: "{prefix}&e{target}&r a &crefusé&r ta requête."
        target: "{prefix}&e{player}&r ne te pistes plus."
      expired: "{prefix}&cPas de requête en cours pour &e{player}&c."

    help:
      noargs: |
        &r- &c/{command} &e{tracker}
        &7  Affiche la liste des joueurs que tu pistes.
      ASK: |
        &r- &c/{command} &e{tracker} &6{ASK} &3<nom>
        &7  Demande à un joueur de le pister.
      START: |
        &r- &c/{command} &e{tracker} &6{START} &3<nom>
        &7  Démarre le pistage d'un joueur (sans demande).
      STOP: |
        &r- &c/{command} &e{tracker} &6{STOP} &3<nom>
        &7  Arrête le pistage d'un joueur.

    target_auto_disabled: "{prefix}&3Tu as atteint &b{target}&3, pistage désactivé dans le tracker &b{tracker}&3."
